### ISSUE TITLE
Crash when message no longer exists

### ISSUE THREAD

**Issue by fixator10** [YofukashiNo/MessageLinkEmbeds#1]
When linked message is deleted after posting, plugin crashes discord
```
97256.c3f19868a32e32cb8beb.js:1 TypeError: Cannot read properties of undefined (reading 'id')
    at renderer.js?t=1712349280772:1:6959
    at Array.map (<anonymous>)
    at renderer.js?t=1712349280772:1:6942
    at aS (58661.cbedde580b7529f6272e.js:12:899964)
    at om (58661.cbedde580b7529f6272e.js:12:911858)
    at of (58661.cbedde580b7529f6272e.js:12:911064)
    at u (58661.cbedde580b7529f6272e.js:12:958560)
    at sB (58661.cbedde580b7529f6272e.js:12:938190)
    at 58661.cbedde580b7529f6272e.js:12:938056
    at sF (58661.cbedde580b7529f6272e.js:12:938064)
    at sC (58661.cbedde580b7529f6272e.js:12:934815)
    at sT (58661.cbedde580b7529f6272e.js:12:933370)
    at x (58661.cbedde580b7529f6272e.js:12:1125228)
    at A (58661.cbedde580b7529f6272e.js:12:1125758)
    at D.<computed> (58661.cbedde580b7529f6272e.js:1:501525)
    at M (58661.cbedde580b7529f6272e.js:1:501290)
    at MessagePort.k (58661.cbedde580b7529f6272e.js:1:501349)```

**Comment by yofukashino** [comment]
fixed in latest release
